[package]
name = "rogue"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.7"
legion = "0.3.1"
ron = "0.8.0"
serde = "1.0.152"
